set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g history-limit 50000
set -g escape-time 0
set -g default-terminal 'tmux-256color'
set -g mode-keys vi
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix
bind g display-popup -E -w 90% -h 90% 'lazygit'
bind | split-window -h
bind - split-window -v
